### ISSUE TITLE
feat: prepare scripts to check and demonstrate integration with Metis chain

### ISSUE THREAD

**Issue by hatskier** [redstone-finance/redstone-evm-connector-examples#4]
- Go through the Metis blockchain docs: https://docs.metis.io/meta/ and understand how to get started with this blockchain
- Create a new `metis` folder in the `scripts` folder
- Put few Node.js scripts (or one script) in the newly created folder. The scripts (or script) should deploy a test contract (which uses RedStone oracles) on the RSK testnet and interact with this contract by calling at least one view function and sending at least one transaction. Both calls should rely on RedStone oracle data

**Comment by cehali** [comment]
Testing Metis on their test network shows that it is rather unstable. It can returns proper value, but sometimes it returns 0 and show error on explorer. Then for some time all transaction throws error: `Data with future timestamps is not allowed`

![image](https://user-images.githubusercontent.com/35804520/175006363-9add128b-b104-4715-ac9f-8acee5138cab.png)


![image](https://user-images.githubusercontent.com/35804520/175006390-d8b31d52-23ce-4c8a-b527-cdf5d520407a.png)

https://stardust-explorer.metis.io/tx/0x2549750326e387b1d551f469a292fde50e20f0b7da60f8dce892191b91d7c1c6
![image](https://user-images.githubusercontent.com/35804520/175006431-cff00be6-7a87-47e5-b1e8-9d2fc92b3319.png)

**Comment by cehali** [comment]
Setting gas limit manually provides the result as on the screenshot (sometimes is valid, most of the time is 0 with transaction error on explorer): 
![image](https://user-images.githubusercontent.com/35804520/175012451-ade057e9-e081-4610-84db-db919f965c0d.png)

**Comment by cehali** [comment]
But when I don't deploy a new contract each time but connect to an existing one, it seems that everything works fine
![image](https://user-images.githubusercontent.com/35804520/175032495-3246a0de-ca4e-4f84-bfb7-18beeb47c3c3.png)

**Comment by cehali** [comment]
Using existing contract but not specifying gas limit manually produces `execution reverted: Data with future timestamps is not allowed` frequently

**Comment by skromez** [comment]
> Setting gas limit manually provides the result as on the screenshot (sometimes is valid, most of the time is 0 with transaction error on explorer): ![image](https://user-images.githubusercontent.com/35804520/175012451-ade057e9-e081-4610-84db-db919f965c0d.png)

I think you didn't wait for the setPrice transaction to end.
I've added this line below `await setPriceTransaction.wait();`
```js
const setPriceTransaction = await wrappedContract.setPrice({ gasLimit: "55000" });
await setPriceTransaction.wait();
```
and it was returning normal value for newly deployed contract
<img width="1051" alt="image" src="https://user-images.githubusercontent.com/42495435/175110978-193d814b-afbd-4971-a11a-fa647d39265b.png">

But yeah sometimes it throws
```js
{
  reason: 'transaction failed',
  code: 'CALL_EXCEPTION',
}
```
 error, don't know the exact reason.

**Comment by cehali** [comment]
When attaching to the existing contract and the gas price is manually set I was able to run the script in intervals of 1 minute for around 5 hours
